######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 29 01:50:56 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cachetable.h \
    mainwindow.h
FORMS += mainwindow.ui
SOURCES += cachetable.cpp \
    main.cpp \
    mainwindow.cpp
