######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 29 02:26:47 2010
######################################################################

QT += xml \
    webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cachetable.h \
    mainwindow.h
FORMS += mainwindow.ui
SOURCES += cachetable.cpp \
    main.cpp \
    mainwindow.cpp
